config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about'

  devise_for :users
  root to: "welcome#index"

  resources :users, only: [:show]

  resources :users, only: [] do
    resources :items, only: [:create, :destroy] do
      put :toggle
    end
  end


end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  validates :name, length: {minimum: 5 }, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    item = @user.items.new(item_params)
    item.user = current_user

    if item.save
      flash[:notice] = "Item saved successfully."
      redirect_to [@user]
    else
      flash[:error] = "Item did not save. Please try again."
      redirect_to [@user]
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @item = @user.items.find(params[:id])

    if @item.destroy
      flash[:notice] = "Item was completed."
    else
      flash[:error] = "Item could not be removed. Try again."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def toggle
    @user = User.find(params[:user_id])
    @item = @user.items.find(params[:item_id])


    if @item.complete
      @item.complete = false
      flash[:notice] = "Item was not completed"
    else
      @item.complete = true
      flash[:notice] = "Item was completed"
    end
    @item.save

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @items = @user.items(current_user)
  end

  def create
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<h4>Add an item to your list</h4>

<%= form_for [user, item] do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'sr-only' %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter your new to-do item" %>
  </div>
  <%= f.submit "Add Item", class: 'btn btn-default pull-right' %>
<% end %>

app/views/items/_item.html.erb
<div class="media" id="item-<%= item.id %>">
  <div class="media-body">
    <small>
      <span style="text-decoration:<%= item.complete ? 'line-through' : ''%>"><%=  item.name %></span>
          : Added <%= time_ago_in_words(item.created_at) %> ago
      <%= link_to "#{item.complete ? 'Undo' : 'Finished'}", user_item_toggle_path(item.user, item), method: :put, remote: true %>
    </small>
  </div>
</div>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-' +<%= @item.id %>).hide();
<% end %>

app/views/items/toggle.js.erb
$('#item-' +<%= @item.id %>).css('text-decoration', 'line-through');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email%></strong>
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to("Sign Out", destroy_user_session_path, :method => :delete) %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path%> |
          <%= link_to "Sign In", new_user_session_path %>
        <% end %>
      </div>
    </ul>
  </div>
  <div class="container">
    <% if flash[:error] %>
      <p><%= flash[:error] %></p>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<p>Populate this view with User info</p>
<%= "Email Address: #{@user.email}" %>
<div>
  <h3>Items</h3>
  <%= render @user.items %>
</div>

<% if current_user %>
  <%= render 'items/form', item: Item.new, user: @user %>
<% end %>

app/views/welcome/about.html.erb
<h1>About Bloccitoff</h1>
<p>A To-Do List Application with Self-Destructive Features</p>
<p>Created by Alex Rolfe</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Bloccitoff</h1>
  <p>Bloccitoff is a resource for managing time sensitive to-do lists</p>
  <p>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row"